"""Hashed otp field added

Revision ID: 023cf9db1030
Revises: 88cc4cb519ce
Create Date: 2025-02-15 17:13:09.294081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023cf9db1030'
down_revision: Union[str, None] = '88cc4cb519ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_opts', sa.Column('hashed_otp', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_opts', 'hashed_otp')
    # ### end Alembic commands ###
